<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RootNamespace>DesktopLyrics</RootNamespace>
    <AssemblyName>LyricBar</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.2" />
  </ItemGroup>

</Project>
